import { autoSplitEmails } from './src/lib/emailParser.js';

const text = `Student Email Batch  8 emails — Mail Priority Classification Dataset  Email 1 of 8  Subject: Backend Developer Internship (Final Year Students)  Dear Student, We are hiring final-year Computer Science students for a Backend Developer Internship. You will work with Node.js, databases, and APIs in real production systems. Strong performers may be offered a full-time role. Apply with your CV. Best regards, Tech Hiring Team  Email 2 of 8  Subject: AI / Machine Learning Research Internship  Hello, A research lab is offering internships in AI and Machine Learning for final-year CS students. You will work on NLP and predictive modeling projects under supervision. Certificate and research exposure included. Regards, Research Coordinator  Email 3 of 8  Subject: Remote Full Stack Developer Internship  Dear Applicant, We are offering a remote internship for students skilled in MERN stack development. Work on live web applications and collaborate with international teams. Flexible hours available. Best, HR Team  Email 4 of 8  Subject: Paid Freelance Projects for Developers  Hi,
We are onboarding student developers for paid freelance projects in web and mobile app development. Perfect for students who want industry experience while studying. Sign up to get matched with projects. Thanks, Project Team  Email 5 of 8  Subject: Congratulations! You have been selected for a Scholarship  Dear Student, You have been randomly selected for a fully funded scholarship. To claim your reward, confirm your details immediately using the link below. Limited time offer! Scholarship Office  Email 6 of 8  Subject: Guaranteed Remote Job – No Experience Needed  Hello, Get a guaranteed tech job within 7 days! No skills or degree required. Just pay a small registration fee to activate your profile. Limited seats available. Career Solutions Team  Email 7 of 8  Subject: Earn $5000 Monthly Using AI Bots (Easy Work)  Hi, Make passive income by using automated AI bots. No coding required. Students are earning daily from home. Join now and start earning instantly. Income Growth Team  Email 8 of 8  Subject: Get Straight A's with Our Assignment Service  Dear Student, We provide guaranteed high grades by completing your assignments and projects for you at low cost. Submit your tasks and relax. Academic Help Desk`

const parts = autoSplitEmails(text);
console.log(`Found ${parts.length} parts`);
parts.forEach((p, i) => {
    console.log(`--- PART ${i + 1} (${p.length} chars) ---`);
    console.log(p.substring(0, 50) + '...');
});
